#!/usr/bin/env sh

remote="$1"
url="$2"

to_push=$(git rev-list --count @{u}..HEAD 2>/dev/null)
if [ "$to_push" = "0" ] 2>/dev/null || [ -z "$to_push" ]; then
  exit 0
fi

local_tag=$(git describe --tags --abbrev=0 2>/dev/null)
remote_tag=$(git ls-remote --tags "$remote" | awk -F/ '{print $3}' | sort -V | tail -n1)

# Если тегов нет — выходим
[ -z "$local_tag" ] && exit 0
[ -z "$remote_tag" ] && exit 0

# Если тег не изменился — выходим
[ "$local_tag" = "$remote_tag" ] && exit 0

echo "############################################################"
echo "🚀  Тег изменился $remote_tag → $local_tag"
echo "    На github.com запустится workflow обновления проекта."
echo "    Через несколько минут придет уведомление в Telegram."
echo "############################################################"

exit 0
