version: "3.9"
services:
  web:
    build: .
    ports:
      - "7878:7878"
    volumes:
      - ./env:/app/env
      - ./lib:/app/lib
      - ./templates:/app/templates
      - ./settings.db:/app/settings.db # Или другой путь к вашей БД
      - ./log:/app/log
    environment:
      - FLASK_APP=wsgi:app
      - PYTHONUNBUFFERED=1 # Для корректного вывода логов
    depends_on:
      - rund

  rund:
    build: .
    volumes:
      - ./env:/app/env
      - ./lib:/app/lib
      - ./settings.db:/app/settings.db # Или другой путь к вашей БД
      - ./log:/app/log
    environment:
      - PYTHONUNBUFFERED=1
    command: python rund.py

