name: Notify container repo on new tag

on:
  push:
    tags:
      - 'v*'

jobs:
  notify-container:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger container repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: vsuh/cron-tg-docker
          event-type: new-reminder-tgm-tag
          client-payload: '{"tag": "${{ github.ref_name }}"}'
